UPDATE Products SET GraphicName = 'modern_php.jpg' WHERE ProductName = 'Modern PHP: New Features and Good Practices';
UPDATE Products SET GraphicName = 'learning_php_mysql_js.jpg' WHERE ProductName = 'Learning PHP, MySQL & JavaScript: With jQuery, CSS & HTML5';
UPDATE Products SET GraphicName = 'css_the_definitive_guide.jpg' WHERE ProductName = 'CSS: The Definitive Guide';
UPDATE Products SET GraphicName = 'js_the_good_part.jpg' WHERE ProductName = 'JavaScript: The Good Parts';
UPDATE Products SET GraphicName = 'learning_js_design_patterns.jpg' WHERE ProductName = 'Learning JavaScript Design Patterns';
UPDATE Products SET GraphicName = 'php_objects_patterns_and_practice.jpg' WHERE ProductName = 'PHP Objects, Patterns, and Practice';
UPDATE Products SET GraphicName = 'php_7_solutions.jpg' WHERE ProductName = 'PHP 7 Solutions: Dynamic Web Design Made Easy';
UPDATE Products SET GraphicName = 'practical_php_7_mysql_8.jpg' WHERE ProductName = 'Practical PHP 7, MySQL 8, and MariaDB Website Databases';
UPDATE Products SET GraphicName = 'the_full_stack_developer.jpg' WHERE ProductName = 'The Full Stack Developer: Your Essential Guide';
UPDATE Products SET GraphicName = 'sql_server_2019_revealed.jpg' WHERE ProductName = 'SQL Server 2019 Revealed: Including Big Data Clusters and Machine Learning';
UPDATE Products SET GraphicName = 'professional_wordpress.jpg' WHERE ProductName = 'Professional WordPress: Design and Development';
UPDATE Products SET GraphicName = 'professional_cs7.jpg' WHERE ProductName = 'Professional C# 7 and .NET Core 2.0';
UPDATE Products SET GraphicName = 'beginning_linux_programming.jpg' WHERE ProductName = 'Beginning Linux Programming';
UPDATE Products SET GraphicName = 'beginning_android_programming.jpg' WHERE ProductName = 'Beginning Android Programming with Android Studio';
UPDATE Products SET GraphicName = 'pro_git.jpg' WHERE ProductName = 'Professional Git';
UPDATE Products SET GraphicName = 'ciritical_thinking.jpg' WHERE ProductName = 'Critical Thinking Skills For Dummies';
UPDATE Products SET GraphicName = 'economics.jpg' WHERE ProductName = 'Economics For Dummies';
UPDATE Products SET GraphicName = 'reading_fin_report.jpg' WHERE ProductName = 'Reading Financial Reports For Dummies';
UPDATE Products SET GraphicName = 'financial_modeling.jpg' WHERE ProductName = 'Financial Modeling in Excel For Dummies';
UPDATE Products SET GraphicName = 'stat_analysis.jpg' WHERE ProductName = 'Statistical Analysis with Excel For Dummies';
UPDATE Products SET GraphicName = 'woocommerce_ex.jpg' WHERE ProductName = 'WooCommerce Explained';
UPDATE Products SET GraphicName = 'wordpress_plugin_ex.jpg' WHERE ProductName = 'Local Web Development With DDEV Explained';
UPDATE Products SET GraphicName = 'local_web_dev_with_ddev.jpg' WHERE ProductName = 'WordPress Plugins Explained';
UPDATE Products SET GraphicName = 'drupal_8_ex.jpg' WHERE ProductName = 'Drupal 8 Explained';
UPDATE Products SET GraphicName = 'multilingual_joomla_ex.jpg' WHERE ProductName = 'Multilingual Joomla Explained';
